---

- name: ensure fogetti-blog folder exists
  file: path={{ blog_dir }} state=directory

- name: Get the fogetti-blog from git
  git: repo=git@github.com:Fogetti/fogetti-blog.git dest={{ blog_dir }} force=yes version=eb5cea79b73bb3cb0cc72a19bf969dc1c689c29f

- name: Install the latest Keystone changes
  npm: name=keystone path={{ blog_dir }}

- name: generate the fogetti-blog '.env' file
  template: src=env.j2 dest={{ blog_dir }}/.env

- name: restart the fogetti-blog
  command: "{{ blog_restart_cmd }}"